### ISSUE TITLE
fatal error: casgstatus: waiting for Gwaiting but is Grunnable

### ISSUE THREAD

**Issue by lemon-mint** [alphadose/ZenQ#9]
A fatal error occurs during benchmarking

`fatal error: casgstatus: waiting for Gwaiting but is Grunnable`

Benchmark Code: https://github.com/lemon-mint/golang-q-benchmark
go version go1.18.4 windows/amd64

```
goos: windows
goarch: amd64
pkg: github.com/lemon-mint/golang-q-benchmark
cpu: Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
BenchmarkZenQ-8   	fatal error: casgstatus: waiting for Gwaiting but is Grunnable

runtime stack:
runtime.throw({0x930baf?, 0xc000084000?})
	C:/Program Files/Go/src/runtime/panic.go:992 +0x76
runtime.casgstatus(0xc0002844e0, 0x4, 0x1)
	C:/Program Files/Go/src/runtime/proc.go:978 +0x385
runtime.ready(0xc0002844e0, 0xc0002844e0?, 0x10?)
	C:/Program Files/Go/src/runtime/proc.go:857 +0x71
runtime.goready.func1()
	C:/Program Files/Go/src/runtime/proc.go:372 +0x26
runtime.systemstack()
	C:/Program Files/Go/src/runtime/asm_amd64.s:469 +0x4e

goroutine 87 [running]:
runtime.systemstack_switch()
	C:/Program Files/Go/src/runtime/asm_amd64.s:436 fp=0xc0003f1df8 sp=0xc0003f1df0 pc=0x8531e0
runtime.goready(0x85df1e?, 0xc00040fce0?)
	C:/Program Files/Go/src/runtime/proc.go:371 +0x47 fp=0xc0003f1e28 sp=0xc0003f1df8 pc=0x82a547
github.com/alphadose/zenq/v2.safe_ready(0x8f1785?)
	G:/go/pkg/mod/github.com/alphadose/zenq/v2@v2.7.0/lib_runtime_linkage.go:176 +0x54 fp=0xc0003f1e50 sp=0xc0003f1e28 pc=0x8efe54
github.com/alphadose/zenq/v2.(*ThreadParker[...]).Ready(0xc000442860?)
	G:/go/pkg/mod/github.com/alphadose/zenq/v2@v2.7.0/thread_parker.go:64 +0x95 fp=0xc0003f1eb8 sp=0xc0003f1e50 pc=0x8f1855
github.com/alphadose/zenq/v2.(*ZenQ[...]).Read(0xc000072640)
	G:/go/pkg/mod/github.com/alphadose/zenq/v2@v2.7.0/zenq.go:188 +0xfa fp=0xc0003f1f20 sp=0xc0003f1eb8 pc=0x8f1a3a
github.com/lemon-mint/golang-q-benchmark.BenchmarkZenQ.func1(0xc00020c020)
	g:/work/golang-q-benchmark/main_test.go:24 +0xb8 fp=0xc0003f1f80 sp=0xc0003f1f20 pc=0x8f0958
testing.(*B).RunParallel.func1()
	C:/Program Files/Go/src/testing/benchmark.go:788 +0xcb fp=0xc0003f1fe0 sp=0xc0003f1f80 pc=0x8ab0cb
runtime.goexit()
	C:/Program Files/Go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc0003f1fe8 sp=0xc0003f1fe0 pc=0x855541
created by testing.(*B).RunParallel
	C:/Program Files/Go/src/testing/benchmark.go:781 +0x105

goroutine 1 [chan receive]:
testing.(*B).doBench(0xc00013c240)
	C:/Program Files/Go/src/testing/benchmark.go:285 +0x7f
testing.(*benchContext).processBench(0xc0000040f0, 0x238?)
	C:/Program Files/Go/src/testing/benchmark.go:589 +0x3aa
testing.(*B).run(0xc00013c240?)
	C:/Program Files/Go/src/testing/benchmark.go:276 +0x67
testing.(*B).Run(0xc00013c000, {0x9280ec?, 0x2f82bb486508?}, 0x932a68)
	C:/Program Files/Go/src/testing/benchmark.go:677 +0x453
testing.runBenchmarks.func1(0xc00013c000?)
	C:/Program Files/Go/src/testing/benchmark.go:550 +0x6e
testing.(*B).runN(0xc00013c000, 0x1)
	C:/Program Files/Go/src/testing/benchmark.go:193 +0x102
testing.runBenchmarks({0x92f7db, 0x28}, 0xa69b60?, {0xa0f3e0, 0x4, 0x40?})
	C:/Program Files/Go/src/testing/benchmark.go:559 +0x3f2
testing.(*M).Run(0xc0000701e0)
	C:/Program Files/Go/src/testing/testing.go:1726 +0x811
main.main()
	_testmain.go:53 +0x1aa
```

![image](https://user-images.githubusercontent.com/55233766/182027420-cde6f350-00c3-495a-9fb0-70f710588a78.png)

**Comment by alphadose** [comment]
@lemon-mint thank you for posting this issue, I am aware of this.

ZenQ works perfectly fine but it doesn't work with some golang aspects like `--race` flag as well as `testing b.RunParallel` in your case

since zenq uses runtime internals but operates in userland, it still doesn't have access to some specific runtime functionalities like `race.Acquire()` hence it will throw errors during benchmarking, running with race flag etc, but it operates fine, here are the benchmarking code which works for ZenQ https://github.com/alphadose/ZenQ/tree/main/benchmarks/simple

**Comment by lemon-mint** [comment]
First of all, thank you for the kind explanation. 
For your information, that error only occurred when GOMAXPROCS exceeds 4.
The benchmark code you gave worked without any problems.

**Comment by alphadose** [comment]
> For your information, that error only occurred when GOMAXPROCS exceeds 4.
@lemon-mint this is really interesting, can you also share the entire dxdiag specs of your machine if possible ? Thanks in advance :)

**Comment by lemon-mint** [comment]
@alphadose 
```
------------------
System Information
------------------
      Time of this report: 8/1/2022, 08:07:08
             Machine name: ___________
               Machine Id: {________-____-____-____-____________}
         Operating System: Windows 10 Pro 64-bit (10.0, Build 19043) (19041.vb_release.191206-1406)
                 Language: Korean (Regional Setting: Korean)
      System Manufacturer: Gigabyte Technology Co., Ltd.
             System Model: Z97X-UD3H
                     BIOS: F7 (type: UEFI)
                Processor: Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 CPUs), ~4.0GHz
                   Memory: 16384MB RAM
      Available OS Memory: 16244MB RAM
                Page File: 8893MB used, 9783MB available
              Windows Dir: C:\WINDOWS
          DirectX Version: DirectX 12
      DX Setup Parameters: Not found
         User DPI Setting: 96 DPI (100 percent)
       System DPI Setting: 96 DPI (100 percent)
          DWM DPI Scaling: Disabled
                 Miracast: Available, with HDCP
Microsoft Graphics Hybrid: Not Supported
 DirectX Database Version: 1.0.8
           DxDiag Version: 10.00.19041.1741 64bit Unicode

------------
DxDiag Notes
------------
      Display Tab 1: No problems found.
        Sound Tab 1: No problems found.
        Sound Tab 2: No problems found.
        Sound Tab 3: No problems found.
        Sound Tab 4: No problems found.
        Sound Tab 5: No problems found.
          Input Tab: No problems found.

--------------------
DirectX Debug Levels
--------------------
Direct3D:    0/4 (retail)
DirectDraw:  0/4 (retail)
DirectInput: 0/5 (retail)
DirectMusic: 0/5 (retail)
DirectPlay:  0/9 (retail)
DirectSound: 0/5 (retail)
DirectShow:  0/6 (retail)


```
